#!/bin/bash
# Workflow automatization tool
# https://github.com/mkrause/workflow

# The absolute path to the directory containing this script
# Source: http://stackoverflow.com/questions/59895
root_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Path to the directory containing the actual workflow script
script_dir="${root_dir}/app/workflow"

# Run workflow
. "${script_dir}/workflow.sh"
